# 1969

In [2]:
import pandas as pd

In [3]:
tot1969 = pd.read_csv("../clean_data/1969ML.csv")
tot1969 = tot1969.drop({"Unnamed: 0", "H", "HR", "BB", "SB", "HA", "HRA", "BBA", "SOA", "E"}, axis=1)
tot1969

      yearID franchID WSWin    R   ERA  WP
0       1969      ATL     N  691  3.53  57
1       1969      BAL     N  779  2.83  67
2       1969      BOS     N  743  3.92  53
3       1969      ANA     N  528  3.54  43
4       1969      CHW     N  625  4.21  41
5       1969      CHC     N  720  3.34  56
6       1969      CIN     N  798  4.11  54
7       1969      CLE     N  573  3.94  38
8       1969      DET     N  701  3.31  55
9       1969      HOU     N  676  3.60  50
10      1969      KCR     N  586  3.72  42
11      1969      LAD     N  645  3.08  52
12      1969      MIN     N  790  3.24  59
13      1969      WSN     N  582  4.33  32
14      1969      NYY     N  562  3.23  49
15      1969      NYM     Y  632  2.99  61
16      1969      OAK     N  740  3.71  54
17      1969      PHI     N  645  4.14  38
18      1969      PIT     N  725  3.61  54
19      1969      SDP     N  468  4.24  32
20      1969      MIL     N  639  4.35  39
21      1969      SFG     N  713  3.26  55
22      1969      STL     N  595  2.94  53
23      1969      TEX     N  694  3.49  53
24      1970      ATL     N  736  4.33  46
25      1970      BAL     Y  792  3.15  66
26      1970      BOS     N  786  3.87  53
27      1970      ANA     N  631  3.48  53
28      1970      CHW     N  633  4.54  34
29      1970      CHC     N  806  3.76  51
...      ...      ...   ...  ...   ...  ..
1230    2015      KCR     Y  724  3.73  58
1231    2015      MIN     N  696  4.07  51
1232    2015      CLE     N  669  3.67  50
1233    2015      CHW     N  622  3.98  46
1234    2015      DET     N  689  4.64  45
1235    2015      TOR     N  891  3.80  57
1236    2015      NYY     N  764  4.03  53
1237    2015      BAL     N  713  4.05  50
1238    2015      TBD     N  644  3.74  49
1239    2015      BOS     N  748  4.31  48
1240    2015      TEX     N  751  4.24  54
1241    2015      HOU     N  729  3.57  53
1242    2015      ANA     N  661  3.94  52
1243    2015      SEA     N  656  4.16  46
1244    2015      OAK     N  694  4.14  41
1245    2015      STL     N  647  2.94  61
1246    2015      PIT     N  697  3.21  60
1247    2015      CHC     N  689  3.36  59
1248    2015      MIL     N  655  4.28  41
1249    2015      CIN     N  640  4.33  39
1250    2015      NYM     N  683  3.43  55
1251    2015      WSN     N  703  3.62  51
1252    2015      FLA     N  613  4.02  43
1253    2015      ATL     N  573  4.41  41
1254    2015      PHI     N  626  4.69  38
1255    2015      LAD     N  667  3.44  56
1256    2015      SFG     N  696  3.72  51
1257    2015      ARI     N  720  4.04  48
1258    2015      SDP     N  650  4.09  45
1259    2015      COL     N  737  5.04  41

[1260 rows x 6 columns]

In [4]:
# Create a function to convert the bats and throws colums to numeric
def bats_throws(col):
   if col == "Y":
       return 1
   else:
       return 0

# Use the `apply()` method to create numeric columns from the bats and throws columns
tot1969['WSWin'] = tot1969['WSWin'].apply(bats_throws)

# Print out the first rows of `master_df`
tot1969

      yearID franchID  WSWin    R   ERA  WP
0       1969      ATL      0  691  3.53  57
1       1969      BAL      0  779  2.83  67
2       1969      BOS      0  743  3.92  53
3       1969      ANA      0  528  3.54  43
4       1969      CHW      0  625  4.21  41
5       1969      CHC      0  720  3.34  56
6       1969      CIN      0  798  4.11  54
7       1969      CLE      0  573  3.94  38
8       1969      DET      0  701  3.31  55
9       1969      HOU      0  676  3.60  50
10      1969      KCR      0  586  3.72  42
11      1969      LAD      0  645  3.08  52
12      1969      MIN      0  790  3.24  59
13      1969      WSN      0  582  4.33  32
14      1969      NYY      0  562  3.23  49
15      1969      NYM      1  632  2.99  61
16      1969      OAK      0  740  3.71  54
17      1969      PHI      0  645  4.14  38
18      1969      PIT      0  725  3.61  54
19      1969      SDP      0  468  4.24  32
20      1969      MIL      0  639  4.35  39
21      1969      SFG      0  713  3.26  55
22      1969      STL      0  595  2.94  53
23      1969      TEX      0  694  3.49  53
24      1970      ATL      0  736  4.33  46
25      1970      BAL      1  792  3.15  66
26      1970      BOS      0  786  3.87  53
27      1970      ANA      0  631  3.48  53
28      1970      CHW      0  633  4.54  34
29      1970      CHC      0  806  3.76  51
...      ...      ...    ...  ...   ...  ..
1230    2015      KCR      1  724  3.73  58
1231    2015      MIN      0  696  4.07  51
1232    2015      CLE      0  669  3.67  50
1233    2015      CHW      0  622  3.98  46
1234    2015      DET      0  689  4.64  45
1235    2015      TOR      0  891  3.80  57
1236    2015      NYY      0  764  4.03  53
1237    2015      BAL      0  713  4.05  50
1238    2015      TBD      0  644  3.74  49
1239    2015      BOS      0  748  4.31  48
1240    2015      TEX      0  751  4.24  54
1241    2015      HOU      0  729  3.57  53
1242    2015      ANA      0  661  3.94  52
1243    2015      SEA      0  656  4.16  46
1244    2015      OAK      0  694  4.14  41
1245    2015      STL      0  647  2.94  61
1246    2015      PIT      0  697  3.21  60
1247    2015      CHC      0  689  3.36  59
1248    2015      MIL      0  655  4.28  41
1249    2015      CIN      0  640  4.33  39
1250    2015      NYM      0  683  3.43  55
1251    2015      WSN      0  703  3.62  51
1252    2015      FLA      0  613  4.02  43
1253    2015      ATL      0  573  4.41  41
1254    2015      PHI      0  626  4.69  38
1255    2015      LAD      0  667  3.44  56
1256    2015      SFG      0  696  3.72  51
1257    2015      ARI      0  720  4.04  48
1258    2015      SDP      0  650  4.09  45
1259    2015      COL      0  737  5.04  41

[1260 rows x 6 columns]

In [5]:
features = tot1969.drop({"franchID", "WSWin", "yearID"}, axis=1)
features

        R   ERA  WP
0     691  3.53  57
1     779  2.83  67
2     743  3.92  53
3     528  3.54  43
4     625  4.21  41
5     720  3.34  56
6     798  4.11  54
7     573  3.94  38
8     701  3.31  55
9     676  3.60  50
10    586  3.72  42
11    645  3.08  52
12    790  3.24  59
13    582  4.33  32
14    562  3.23  49
15    632  2.99  61
16    740  3.71  54
17    645  4.14  38
18    725  3.61  54
19    468  4.24  32
20    639  4.35  39
21    713  3.26  55
22    595  2.94  53
23    694  3.49  53
24    736  4.33  46
25    792  3.15  66
26    786  3.87  53
27    631  3.48  53
28    633  4.54  34
29    806  3.76  51
...   ...   ...  ..
1230  724  3.73  58
1231  696  4.07  51
1232  669  3.67  50
1233  622  3.98  46
1234  689  4.64  45
1235  891  3.80  57
1236  764  4.03  53
1237  713  4.05  50
1238  644  3.74  49
1239  748  4.31  48
1240  751  4.24  54
1241  729  3.57  53
1242  661  3.94  52
1243  656  4.16  46
1244  694  4.14  41
1245  647  2.94  61
1246  697  3.21  60
1247  689  3.36  59
1248  655  4.28  41
1249  640  4.33  39
1250  683  3.43  55
1251  703  3.62  51
1252  613  4.02  43
1253  573  4.41  41
1254  626  4.69  38
1255  667  3.44  56
1256  696  3.72  51
1257  720  4.04  48
1258  650  4.09  45
1259  737  5.04  41

[1260 rows x 3 columns]

In [6]:
# Create `target` Series
target = tot1969['WSWin']
target

0       0
1       0
2       0
3       0
4       0
5       0
6       0
7       0
8       0
9       0
10      0
11      0
12      0
13      0
14      0
15      1
16      0
17      0
18      0
19      0
20      0
21      0
22      0
23      0
24      0
25      1
26      0
27      0
28      0
29      0
       ..
1230    1
1231    0
1232    0
1233    0
1234    0
1235    0
1236    0
1237    0
1238    0
1239    0
1240    0
1241    0
1242    0
1243    0
1244    0
1245    0
1246    0
1247    0
1248    0
1249    0
1250    0
1251    0
1252    0
1253    0
1254    0
1255    0
1256    0
1257    0
1258    0
1259    0
Name: WSWin, Length: 1260, dtype: int64

In [7]:
# Import cross_val_predict, KFold and LogisticRegression from 'sklearn'
from sklearn.cross_validation import cross_val_predict, KFold
from sklearn.linear_model import LogisticRegression

# Create Logistic Regression model
lr = LogisticRegression(class_weight='balanced')

# Create an instance of the KFold class
kf = KFold(features.shape[0], random_state=1)

# Create predictions using cross validation
predictions_lr = cross_val_predict(lr, features, target, cv=kf)

/Applications/anaconda3/envs/PythonData/lib/python3.6/site-packages/sklearn/cross_validation.py:41: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)

In [8]:
import numpy as np

# Convert predictions and target to NumPy arrays
np_predictions_lr = np.asarray(predictions_lr)
np_target = target.as_matrix()

In [9]:
# Determine True Positive count
tp_filter_lr = (np_predictions_lr == 1) & (np_target == 1)
tp_lr = len(np_predictions_lr[tp_filter_lr])

# Determine False Negative count
fn_filter_lr = (np_predictions_lr == 0) & (np_target == 1)
fn_lr = len(np_predictions_lr[fn_filter_lr])

# Determine False Positive count
fp_filter_lr = (np_predictions_lr == 1) & (np_target == 0)
fp_lr = len(np_predictions_lr[fp_filter_lr])

# Determine True Negative count
tn_filter_lr = (np_predictions_lr == 0) & (np_target == 0)
tn_lr = len(np_predictions_lr[tn_filter_lr])

# Determine True Positive rate
tpr_lr = tp_lr / (tp_lr + fn_lr)

# Determine False Negative rate
fnr_lr = fn_lr / (fn_lr + tp_lr)

# Determine False Positive rate
fpr_lr = fp_lr / (fp_lr + tn_lr)

# Print each count
print(tp_lr)
print(fn_lr)
print(fp_lr)

# Print each rate
print(tpr_lr)
print(fnr_lr)
print(fpr_lr)

38
8
298
0.8260869565217391
0.17391304347826086
0.24546952224052718

In [11]:
new_data = tot1969
new_features = features

In [12]:
# Fit the Random Forest model
lr.fit(features, target)

# Estimate probabilities of Hall of Fame induction
probabilities = lr.predict_proba(new_features)

In [13]:
# Convert predictions to a DataFrame
WS_predictions = pd.DataFrame(probabilities[:,1])

# Sort the DataFrame (descending)
WS_predictions = WS_predictions.sort_values(0, ascending=False)

WS_predictions['Probability'] = WS_predictions[0]

# Print 50 highest probability HoF inductees from still eligible players
for i, row in WS_predictions.head(50).iterrows():
   prob = ' '.join(('WS Probability =', str(row['Probability'])))
   print('')
   print(prob)
   print(new_data.iloc[i,1:27])

WS Probability = 0.983876728628
franchID     SEA
WSWin          0
R            927
ERA         3.54
WP            71
Name: 834, dtype: object

WS Probability = 0.980273166603
franchID     BAL
WSWin          0
R            779
ERA         2.83
WP            67
Name: 1, dtype: object

WS Probability = 0.975101096564
franchID     NYY
WSWin          1
R            965
ERA         3.82
WP            70
Name: 738, dtype: object

WS Probability = 0.963926816716
franchID     NYM
WSWin          1
R            783
ERA         3.11
WP            66
Name: 442, dtype: object

WS Probability = 0.963168810458
franchID     BAL
WSWin          1
R            792
ERA         3.15
WP            66
Name: 25, dtype: object

WS Probability = 0.958408565665
franchID     CIN
WSWin          1
R            840
ERA         3.37
WP            66
Name: 150, dtype: object

WS Probability = 0.957195076641
franchID     ATL
WSWin          0
R            826
ERA         3.25
WP            65
Name: 722, dtype: object

WS Probability = 0.950419452062
franchID     LAD
WSWin          0
R            798
ERA         2.97
WP            62
Name: 131, dtype: object

WS Probability = 0.944693851255
franchID     CLE
WSWin          0
R            840
ERA         3.83
WP            69
Name: 643, dtype: object

WS Probability = 0.944072178461
franchID     ATL
WSWin          0
R            767
ERA         3.14
WP            64
Name: 608, dtype: object

WS Probability = 0.942143566842
franchID     BAL
WSWin          0
R            742
ERA         2.99
WP            63
Name: 49, dtype: object

WS Probability = 0.932109337811
franchID     PHI
WSWin          0
R            770
ERA         3.08
WP            62
Name: 186, dtype: object

WS Probability = 0.928834515148
franchID     BAL
WSWin          0
R            757
ERA         3.26
WP            64
Name: 245, dtype: object

WS Probability = 0.928356869783
franchID     NYM
WSWin          0
R            703
ERA         2.91
WP            62
Name: 494, dtype: object

WS Probability = 0.928095366085
franchID     ATL
WSWin          0
R            791
ERA         3.18
WP            62
Name: 693, dtype: object

WS Probability = 0.927584653169
franchID     DET
WSWin          1
R            829
ERA         3.49
WP            64
Name: 382, dtype: object

WS Probability = 0.924693595608
franchID     PIT
WSWin          0
R            691
ERA         2.81
WP            61
Name: 91, dtype: object

WS Probability = 0.923069966009
franchID     OAK
WSWin          0
R            800
ERA         3.44
WP            64
Name: 495, dtype: object

WS Probability = 0.921702515272
franchID    STL
WSWin         0
R           747
ERA         3.1
WP           62
Name: 423, dtype: object

WS Probability = 0.9200009163
franchID    HOU
WSWin         0
R           874
ERA         3.5
WP           62
Name: 732, dtype: object

WS Probability = 0.918761686323
franchID     PHI
WSWin          0
R            713
ERA         3.02
WP            62
Name: 1130, dtype: object

WS Probability = 0.91822552047
franchID     OAK
WSWin          0
R            733
ERA         3.18
WP            63
Name: 547, dtype: object

WS Probability = 0.912174553262
franchID     OAK
WSWin          0
R            884
ERA         3.59
WP            62
Name: 830, dtype: object

WS Probability = 0.911881413861
franchID     CIN
WSWin          1
R            857
ERA         3.51
WP            62
Name: 174, dtype: object

WS Probability = 0.907729988899
franchID     OAK
WSWin          1
R            604
ERA         2.58
WP            60
Name: 89, dtype: object

WS Probability = 0.905500842036
franchID     OAK
WSWin          0
R            691
ERA         3.05
WP            62
Name: 65, dtype: object

WS Probability = 0.903855713006
franchID     STL
WSWin          0
R            855
ERA         3.75
WP            64
Name: 926, dtype: object

WS Probability = 0.901280265654
franchID     ATL
WSWin          0
R            708
ERA         3.13
WP            62
Name: 842, dtype: object

WS Probability = 0.900750542401
franchID     ATL
WSWin          0
R            840
ERA         3.63
WP            63
Name: 752, dtype: object

WS Probability = 0.899080762874
franchID     NYY
WSWin          0
R            820
ERA         3.58
WP            63
Name: 285, dtype: object

WS Probability = 0.894574309868
franchID     OAK
WSWin          1
R            712
ERA         3.09
WP            61
Name: 521, dtype: object

WS Probability = 0.894509855115
franchID     KCR
WSWin          0
R            822
ERA         3.52
WP            62
Name: 202, dtype: object

WS Probability = 0.891299833876
franchID     NYY
WSWin          1
R            735
ERA         3.18
WP            61
Name: 233, dtype: object

WS Probability = 0.89009442295
franchID     NYY
WSWin          0
R            897
ERA         3.87
WP            63
Name: 858, dtype: object

WS Probability = 0.888283772652
franchID     SFG
WSWin          0
R            808
ERA         3.61
WP            63
Name: 632, dtype: object

WS Probability = 0.887577234554
franchID     BAL
WSWin          0
R            754
ERA         3.07
WP            59
Name: 97, dtype: object

WS Probability = 0.887052187486
franchID     NYY
WSWin          0
R            730
ERA         3.19
WP            61
Name: 183, dtype: object

WS Probability = 0.886624184465
franchID     STL
WSWin          0
R            647
ERA         2.94
WP            61
Name: 1245, dtype: object

WS Probability = 0.885963506347
franchID     LAD
WSWin          0
R            769
ERA         3.22
WP            60
Name: 203, dtype: object

WS Probability = 0.881492050226
franchID     TOR
WSWin          0
R            759
ERA         3.31
WP            61
Name: 425, dtype: object

WS Probability = 0.880285020853
franchID     ARI
WSWin          0
R            908
ERA         3.77
WP            61
Name: 751, dtype: object

WS Probability = 0.876835802248
franchID     MIN
WSWin          0
R            790
ERA         3.24
WP            59
Name: 12, dtype: object

WS Probability = 0.874660466401
franchID     PHI
WSWin          0
R            847
ERA         3.71
WP            62
Name: 210, dtype: object

WS Probability = 0.874146319307
franchID     STL
WSWin          0
R            805
ERA         3.49
WP            61
Name: 955, dtype: object

WS Probability = 0.871245303421
franchID     OAK
WSWin          0
R            800
ERA         3.68
WP            63
Name: 860, dtype: object

WS Probability = 0.870730869031
franchID     OAK
WSWin          0
R            758
ERA         3.27
WP            60
Name: 161, dtype: object

WS Probability = 0.870696753188
franchID     CIN
WSWin          0
R            707
ERA         3.21
WP            61
Name: 78, dtype: object

WS Probability = 0.870231665796
franchID     MIN
WSWin          0
R            744
ERA         3.23
WP            60
Name: 36, dtype: object

WS Probability = 0.869118196659
franchID     NYM
WSWin          1
R            632
ERA         2.99
WP            61
Name: 15, dtype: object

WS Probability = 0.866247542947
franchID     NYY
WSWin          1
R            831
ERA         3.61
WP            61
Name: 207, dtype: object