# Runs

In [15]:
# Import dependencies.
import plotly.plotly as py
import plotly.graph_objs as go

import numpy as np
import pandas as pd
import statistics

In [2]:
import plotly
plotly.tools.set_credentials_file(username='', api_key='')

### Open up the 1905 and 1969 csv files and inspect.

In [3]:
# Open up the csv for World Series Winners Runs from 1905 onwards.
df2a = pd.read_csv("../clean_data/wswin_1905Runs.csv")
df2a = df2a.drop("Unnamed: 0", axis=1)
df2a = df2a.sort_values(["Runs"], ascending = True)
df2a

    Runs  Count  Frequency
64   450      1   0.009091
13   474      1   0.009091
11   550      1   0.009091
1    570      1   0.009091
2    574      1   0.009091
14   577      1   0.009091
57   604      1   0.009091
51   608      1   0.009091
3    624      1   0.009091
69   628      1   0.009091
54   632      1   0.009091
37   633      1   0.009091
28   636      1   0.009091
49   640      1   0.009091
73   645      1   0.009091
12   656      1   0.009091
9    657      1   0.009091
90   665      1   0.009091
10   669      2   0.018182
53   671      1   0.009091
5    673      1   0.009091
65   685      1   0.009091
66   687      1   0.009091
59   689      1   0.009091
70   693      1   0.009091
52   695      1   0.009091
86   697      1   0.009091
4    699      1   0.009091
46   705      1   0.009091
34   707      1   0.009091
..   ...    ...        ...
18   823      1   0.009091
48   827      1   0.009091
39   829      2   0.018182
35   830      1   0.009091
60   831      1   0.009091
16   840      3   0.027273
72   847      1   0.009091
79   851      1   0.009091
17   852      1   0.009091
89   853      1   0.009091
15   857      4   0.036364
6    861      1   0.009091
84   867      1   0.009091
74   871      2   0.018182
23   894      1   0.009091
77   900      1   0.009091
24   901      1   0.009091
20   912      1   0.009091
40   914      1   0.009091
85   915      1   0.009091
29   919      1   0.009091
81   949      1   0.009091
25   951      1   0.009091
76   965      1   0.009091
32   966      1   0.009091
33   967      1   0.009091
22   975      1   0.009091
31   979      1   0.009091
27  1002      1   0.009091
30  1065      1   0.009091

[92 rows x 3 columns]

In [4]:
# Open up the csv for all teams Runs from 1905 onwards.
df2b = pd.read_csv("../clean_data/nowswin_1905Runs.csv")
df2b = df2b.drop("Unnamed: 0", axis=1)
df2b = df2b.sort_values(["Runs"], ascending = True)
df2b

     Runs  Count  Frequency
429   329      1   0.000454
423   348      1   0.000454
151   360      1   0.000454
416   370      1   0.000454
53    371      1   0.000454
42    377      1   0.000454
420   378      1   0.000454
67    380      1   0.000454
427   382      1   0.000454
338   394      2   0.000907
414   395      1   0.000454
419   397      1   0.000454
426   407      1   0.000454
17    408      1   0.000454
154   412      1   0.000454
40    419      1   0.000454
422   421      1   0.000454
152   424      1   0.000454
157   426      2   0.000907
418   427      2   0.000907
415   429      1   0.000454
155   430      1   0.000454
417   431      1   0.000454
57    435      1   0.000454
65    441      1   0.000454
421   443      1   0.000454
56    444      1   0.000454
29    446      1   0.000454
141   447      1   0.000454
80    451      1   0.000454
..    ...    ...        ...
177   925      3   0.001361
251   926      1   0.000454
285   927      2   0.000907
442   928      2   0.000907
483   930      1   0.000454
311   935      1   0.000454
471   938      1   0.000454
456   940      1   0.000454
263   944      1   0.000454
466   945      1   0.000454
472   947      1   0.000454
179   948      1   0.000454
441   949      1   0.000454
469   950      1   0.000454
444   952      1   0.000454
372   955      1   0.000454
291   958      1   0.000454
261   959      1   0.000454
445   961      2   0.000907
470   968      2   0.000907
468   978      1   0.000454
278   981      1   0.000454
249   982      1   0.000454
448   993      1   0.000454
258   998      1   0.000454
265  1004      1   0.000454
460  1009      1   0.000454
358  1027      1   0.000454
262  1062      1   0.000454
270  1067      1   0.000454

[487 rows x 3 columns]

In [5]:
# Open up the csv for World Series Winners Runs from 1969 onwards.
df3a = pd.read_csv("../clean_data/wswin_1969Runs.csv")
df3a = df3a.drop("Unnamed: 0", axis=1)
df3a = df3a.sort_values(["Runs"], ascending = True)
df3a

    Runs  Count  Frequency
12   450      1   0.021739
3    604      1   0.021739
19   628      1   0.021739
0    632      1   0.021739
25   645      1   0.021739
42   665      1   0.021739
13   685      1   0.021739
16   687      1   0.021739
5    689      1   0.021739
21   693      1   0.021739
38   697      1   0.021739
20   712      1   0.021739
40   718      1   0.021739
43   724      1   0.021739
11   728      1   0.021739
9    735      1   0.021739
27   740      1   0.021739
34   741      1   0.021739
32   751      1   0.021739
4    758      1   0.021739
39   762      1   0.021739
10   775      1   0.021739
22   776      1   0.021739
23   780      1   0.021739
35   781      1   0.021739
17   783      1   0.021739
18   786      1   0.021739
2    788      1   0.021739
1    792      1   0.021739
14   799      2   0.043478
30   818      1   0.021739
15   829      1   0.021739
8    831      1   0.021739
6    840      1   0.021739
24   847      1   0.021739
31   851      1   0.021739
41   853      1   0.021739
7    857      1   0.021739
36   867      1   0.021739
26   871      2   0.043478
29   900      1   0.021739
37   915      1   0.021739
33   949      1   0.021739
28   965      1   0.021739

In [6]:
# Open up the csv for all teams Runs from 1969 onwards.
df3b = pd.read_csv("../clean_data/nowswin_1969Runs.csv")
df3b = df3b.drop("Unnamed: 0", axis=1)
df3b = df3b.sort_values(["Runs"], ascending = True)
df3b

     Runs  Count  Frequency
206   329      1   0.000824
199   348      1   0.000824
190   370      1   0.000824
196   378      1   0.000824
203   382      1   0.000824
194   394      1   0.000824
187   395      1   0.000824
195   397      1   0.000824
202   407      1   0.000824
198   421      1   0.000824
204   426      1   0.000824
193   427      2   0.001647
188   429      1   0.000824
192   431      1   0.000824
197   443      1   0.000824
205   452      1   0.000824
65    454      1   0.000824
200   458      1   0.000824
80    461      1   0.000824
191   464      2   0.001647
17    468      1   0.000824
69    472      1   0.000824
189   476      2   0.001647
58    486      1   0.000824
77    488      1   0.000824
201   491      1   0.000824
73    493      2   0.001647
76    503      1   0.000824
45    511      1   0.000824
74    513      3   0.002471
..    ...    ...        ...
214   891      3   0.002471
365   892      1   0.000824
328   893      1   0.000824
302   894      2   0.001647
250   896      1   0.000824
344   897      3   0.002471
298   898      1   0.000824
284   899      1   0.000824
369   901      1   0.000824
323   906      1   0.000824
341   907      2   0.001647
319   908      1   0.000824
358   910      1   0.000824
309   923      2   0.001647
311   925      2   0.001647
346   927      1   0.000824
297   928      2   0.001647
363   930      1   0.000824
338   938      1   0.000824
317   940      1   0.000824
330   945      1   0.000824
340   947      1   0.000824
296   949      1   0.000824
336   950      1   0.000824
300   952      1   0.000824
301   961      2   0.001647
337   968      2   0.001647
334   978      1   0.000824
304   993      1   0.000824
322  1009      1   0.000824

[377 rows x 3 columns]

### Pull data into lists from tables.

In [7]:
Runs2a = list(df2a["Runs"])
frequency2a = list(df2a["Count"])

In [8]:
Runs2b = list(df2b["Runs"])
frequency2b = list(df2b["Count"])

In [9]:
Runs3a = list(df3a["Runs"])
frequency3a = list(df3a["Count"])

In [10]:
Runs3b = list(df3b["Runs"])
frequency3b = list(df3b["Count"])

### Graph the data.

In [11]:
trace1 = go.Scatter(
    x = Runs2a,
    y = frequency2a,
    mode = "lines",
    fill = "toself",
    fillcolor = "rgb(28, 74, 175)",
    marker = dict(
        color = "rgb(28, 74, 175)"
    ),
    name = "World Series Winners"
)

trace2 = go.Scatter(
    x = Runs2b, 
    y = frequency2b,
    mode = "lines",
    fill = "toself",
    marker = dict(
        color = "rgba(192, 57, 43, 0.5)"
    ),
    name = "Non-World Series Winning Teams"
)

data = [trace1, trace2]
layout = go.Layout(
    xaxis = {"title": "Runs"},
    yaxis = {"title": "Frequency"},
    barmode = "group",
    title = "World Series Runs (1905-2015)"
)

fig = go.Figure(data = data, layout = layout)
py.iplot(fig, filename="1905Runs")

In [12]:
trace1 = go.Scatter(
    x = Runs3a,
    y = frequency3a,
    mode = "lines",
    fill = "toself",
    fillcolor = "rgb(28, 74, 175)",
    marker = dict(
        color = "rgb(28, 74, 175)"
    ),
    name = "World Series Winners"
)

trace2 = go.Scatter(
    x = Runs3b, 
    y = frequency3b,
    mode = "lines",
    fill = "toself",
    marker = dict(
        color = "rgba(192, 57, 43, 0.5)"
    ),
    name = "Non-World Series Winning Teams"
)

data = [trace1, trace2]
layout = go.Layout(
    xaxis = {"title": "Runs"},
    yaxis = {"title": "Frequency"},
    barmode = "group",
    title = "World Series Runs (1969-2015)"
)

fig = go.Figure(data = data, layout = layout)
py.iplot(fig, filename="1969Runs")

## Perform basic stats analysis.
    # Calculate mean and standard deviation of Runs of the World Series winning population.
    # Calculate mean and standard deviation of Runs of the World Series non-winning population.
    # Calculate confidence interval.

### 1905.

In [13]:
# Calculate mean of Runs of World Series winning teams for 1905 onwards.
wswin_mean1905 = round((np.mean(df2a["Runs"])), 2)
wswin_mean1905

767.09

In [16]:
# Calculate standard deviation of World Series winning teams for 1905 onwards.
wswin_dev1905 = round((statistics.stdev(df2a["Runs"])), 2)
wswin_dev1905

119.98

In [24]:
# Calculate number of entries in World Series winning teams for 1905 onwards.
wswin_len1905 = df2a["Count"].sum()
wswin_len1905

110

In [18]:
# Calculate mean Runs fo non-World Series winning teams for 1905 onwards.
nowswin_mean1905 = round((np.mean(df2b["Runs"])), 2)
nowswin_mean1905

687.85

In [19]:
# Calculate standard deviation of non-World Series winning teams for 1905 onwards.
nowswin_dev1905 = round((statistics.stdev(df2b["Runs"])), 2)
nowswin_dev1905

154.62

In [25]:
# Calculate total number of non-World Series winning teams for 1905 onwards.
nowswin_len1905 = df2b["Count"].sum()
nowswin_len1905

2204

### Determine significance of 1905 winners and non-winners.

In [21]:
# Calculate variance for each sample group.
wswin_variance1905 = (wswin_dev1905)**2
nowswin_variance1905 = (nowswin_dev1905)**2
print (wswin_variance1905)
print (nowswin_variance1905)

14395.200400000002
23907.3444

    # The hypothesis I'm testing is that World Series winners tend to have higher Runs than non-World Series teams.
    # That means:
        # null hypothesis is:  u1 < u2....  or u1 - u2 <= 0
        # hypothesis to test is:  u1 - u2 > 0
    # This stands to be a right tail test.

In [26]:
# Calculate Z.
num_1905 = wswin_mean1905 - nowswin_mean1905
dem_1905 = ((wswin_variance1905/wswin_len1905) + (nowswin_variance1905/nowswin_len1905)) ** 0.5
Z_1905 = num_1905/dem_1905
Z_1905

6.656409998756957

    # Because this is a right tail, find negative Z.  Then look up on table.

### Look up the Z value on table.  P-Value is < 0.00001
### This means that I can say that if the confidence level is 99.99% (alpha = 0.0001) that World Series teams definitely has a lower Runs than all other teams.... because p<= alpha (reject null hypothesis; accept test hypothesis).

### 1969.

In [28]:
# Calculate mean of Runs of World Series winning teams for 1969 onwards.
wswin_mean1969 = round((np.mean(df3a["Runs"])), 2)
wswin_mean1969

765.84

In [29]:
# Calculate standard deviation of World Series winning teams for 1969 onwards.
wswin_dev1969 = round((statistics.stdev(df3a["Runs"])), 2)
wswin_dev1969

97.86

In [30]:
# Calculate number of World Series winning teams for 1969 onwards.
wswin_len1969 = df3a["Count"].sum()
wswin_len1969

46

In [32]:
# Calculate mean of non-World Series winning teams for 1969 onwards.
nowswin_mean1969 = round((np.mean(df3b["Runs"])), 2)
nowswin_mean1969

707.0

In [33]:
# Calculate standard deviation of non-World Series winning teams for 1969 onwards.
nowswin_dev1969 = round((statistics.stdev(df3b["Runs"])), 2)
nowswin_dev1969

133.16

In [35]:
# Calculate number of non-World Series winning teams for 1969 onwards.
nowswin_len1969 = df3b["Count"].sum()
nowswin_len1969

1214

### Determine significance of 1969 winners and non-winners.

In [36]:
# Calculate variance for each sample group.
wswin_variance1969 = (wswin_dev1969)**2
nowswin_variance1969 = (nowswin_dev1969)**2
print (wswin_variance1969)
print (nowswin_variance1969)

9576.5796
17731.5856

    # The hypothesis I'm testing is that World Series winners tend to have higher Runs than non-World Series teams.
    # That means:
        # null hypothesis is:  u1 < u2....  or u1 - u2 <= 0
        # hypothesis to test is:  u1 - u2 > 0
    # This stands to be a right tail test.

In [38]:
# Calculate Z.
num_1969 = wswin_mean1969 - nowswin_mean1969
dem_1969 = ((wswin_variance1969/wswin_len1969) + (nowswin_variance1969/nowswin_len1969)) ** 0.5
Z_1969 = num_1969/dem_1969
Z_1969

3.9420528906854058

    # Because this is a right tail, find negative Z.  Then look up on table.

### Look up the Z value on table.  P-Value is < 0.00001
### This means that I can say that if the confidence level is 99.99% (alpha = 0.0001) that World Series teams definitely has a lower runs than all other teams.... because p<= alpha (reject null hypothesis; accept test hypothesis).