### Import Teams.csv and isolate the average number of wins.
    # Want frequency v. win percentage of teams

In [1]:
# Import dependencies.
import pandas as pd
from collections import Counter

In [2]:
# Open up the csv and inspect.
df = pd.read_csv("../baseball-databank/Teams.csv")
df

,yearID,lgID,teamID,franchID,divID,Rank,G,Ghome,W,L,...,DP,FP,name,park,attendance,BPF,PPF,teamIDBR,teamIDlahman45,teamIDretro
0,1871,NaN,BS1,BNA,NaN,3,31,NaN,20,10,...,NaN,0.830,Boston Red Stockings,South End Grounds I,NaN,103,98,BOS,BS1,BS1
1,1871,NaN,CH1,CNA,NaN,2,28,NaN,19,9,...,NaN,0.820,Chicago White Stockings,Union Base-Ball Grounds,NaN,104,102,CHI,CH1,CH1
2,1871,NaN,CL1,CFC,NaN,8,29,NaN,10,19,...,NaN,0.810,Cleveland Forest Citys,National Association Grounds,NaN,96,100,CLE,CL1,CL1
3,1871,NaN,FW1,KEK,NaN,7,19,NaN,7,12,...,NaN,0.800,Fort Wayne Kekiongas,Hamilton Field,NaN,101,107,KEK,FW1,FW1
4,1871,NaN,NY2,NNA,NaN,5,33,NaN,16,17,...,NaN,0.830,New York Mutuals,Union Grounds (Brooklyn),NaN,90,88,NYU,NY2,NY2
5,1871,NaN,PH1,PNA,NaN,1,28,NaN,21,7,...,NaN,0.840,Philadelphia Athletics,Jefferson Street Grounds,NaN,102,98,ATH,PH1,PH1
6,1871,NaN,RC1,ROK,NaN,9,25,NaN,4,21,...,NaN,0.820,Rockford Forest Citys,Agricultural Society Fair Grounds,NaN,97,99,ROK,RC1,RC1
7,1871,NaN,TRO,TRO,NaN,6,29,NaN,13,15,...,NaN,0.840,Troy Haymakers,Haymakers' Grounds,NaN,101,100,TRO,TRO,TRO
8,1871,NaN,WS3,OLY,NaN,4,32,NaN,15,15,...,NaN,0.850,Washington Olympics,Olympics Grounds,NaN,94,98,OLY,WS3,WS3
9,1872,NaN,BL1,BLC,NaN,2,58,NaN,35,19,...,NaN,0.820,Baltimore Canaries,Newington Park,NaN,106,102,BAL,BL1,BL1
10,1872,NaN,BR1,ECK,NaN,9,29,NaN,3,26,...,NaN,0.790,Brooklyn Eckfords,Union Grounds,NaN,87,96,ECK,BR1,BR1
11,1872,NaN,BR2,BRA,NaN,6,37,NaN,9,28,...,NaN,0.810,Brooklyn Atlantics,Capitoline Grounds,NaN,115,122,BRA,BR2,BR2
12,1872,NaN,BS1,BNA,NaN,1,48,NaN,39,8,...,NaN,0.870,Boston Red Stockings,South End Grounds I,NaN,105,100,BOS,BS1,BS1
13,1872,NaN,CL1,CFC,NaN,7,22,NaN,6,16,...,NaN,0.820,Cleveland Forest Citys,National Association Grounds,NaN,96,100,CLE,CL1,CL1
14,1872,NaN,MID,MAN,NaN,8,24,NaN,5,19,...,NaN,0.800,Middletown Mansfields,Mansfield Club Grounds,NaN,98,103,MAN,MID,MID
15,1872,NaN,NY2,NNA,NaN,3,56,NaN,34,20,...,NaN,0.860,New York Mutuals,Union Grounds (Brooklyn),NaN,93,92,NYU,NY2,NY2
16,1872,NaN,PH1,PNA,NaN,4,47,NaN,30,14,...,NaN,0.850,Philadelphia Athletics,Jefferson Street Grounds,NaN,102,100,ATH,PH1,PH1
17,1872,NaN,TRO,TRO,NaN,5,25,NaN,15,10,...,NaN,0.860,Troy Haymakers,Haymakers' Grounds,NaN,101,100,TRO,TRO,TRO
18,1872,NaN,WS3,OLY,NaN,10,9,NaN,2,7,...,NaN,0.780,Washington Olympics,Olympics Grounds,NaN,94,98,OLY,WS3,WS3
19,1872,NaN,WS4,NAT,NaN,11,11,NaN,0,11,...,NaN,0.760,Washington Nationals,Nationals Grounds,NaN,129,141,NAT,WS4,WS4
20,1873,NaN,BL1,BLC,NaN,3,57,NaN,34,22,...,NaN,0.850,Baltimore Canaries,Newington Park,NaN,101,102,BAL,BL1,BL1
21,1873,NaN,BL4,MAR,NaN,9,6,NaN,0,6,...,NaN,0.760,Baltimore Marylands,Newington Park,NaN,77,99,MAR,BL4,BL4
22,1873,NaN,BR2,BRA,NaN,6,55,NaN,17,37,...,NaN,0.820,Brooklyn Atlantics,Union Grounds,NaN,90,94,BRA,BR2,BR2
23,1873,NaN,BS1,BNA,NaN,1,60,NaN,43,16,...,NaN,0.830,Boston Red Stockings,South End Grounds I,NaN,106,100,BOS,BS1,BS1
24,1873,NaN,ELI,RES,NaN,8,23,NaN,2,21,...,NaN,0.780,Elizabeth Resolutes,Waverly Fairgrounds,NaN,92,103,RES,ELI,ELI
25,1873,NaN,NY2,NNA,NaN,4,53,NaN,29,24,...,NaN,0.820,New York Mutuals,Union Grounds (Brooklyn),NaN,98,96,NYU,NY2,NY2
26,1873,NaN,PH1,PNA,NaN,5,52,NaN,28,23,...,NaN,0.840,Philadelphia Athletics,Jefferson Street Grounds,NaN,108,105,ATH,PH1,PH1
27,1873,NaN,PH2,PWS,NaN,2,53,NaN,36,17,...,NaN,0.840,Philadelphia Whites,Jefferson Street Grounds,NaN,103,101,PHI,PH2,PH2
28,1873,NaN,WS5,WBL,NaN,7,39,NaN,8,31,...,NaN,0.840,Washington Blue Legs,Olympics Grounds,NaN,96,102,WAS,WS5,WS5
29,1874,NaN,BL1,BLC,NaN,8,47,NaN,9,38,...,NaN,0.810,Baltimore Canaries,Newington Park,NaN,102,104,BAL,BL1,BL1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2775,2015,AL,KCA,KCR,C,1,162,81.0,95,67,...,138.0,0.985,Kansas City Royals,Kauffman Stadium,2708549.0,104,103,KCR,KCA,KCA
2776,2015,AL,MIN,MIN,C,2,162,81.0,83,79,...,150.0,0.986,Minnesota Twins,Target Field,2220054.0,103,104,MIN,MIN,MIN
2777,2015,AL,CLE,CLE,C,3,161,80.0,81,80,...,136.0,0.987,Cleveland Indians,Progressive Field,1388905.0,106,106,CLE,CLE,CLE
2778,2015,AL,CHA,CHW,C,4,162,81.0,76,86,...,159.0,0.983,Chicago White Sox,U.S. Cellular Field,1755810.0,97,96,CHW,CHA,CHA
2779,2015,AL,DET,DET,C,5,161,81.0,74,87,...,165.0,0.986,Detroit Tigers,Comerica Park,2726048.0,97,98,DET,DET,DET
2780,2015,AL,TOR,TOR,E,1,162,81.0,93,69,...,145.0,0.985,Toronto Blue Jays,Rogers Centre,2794891.0,99,98,TOR,TOR,TOR
2781,2015,AL,NYA,NYY,E,2,162,81.0,87,75,...,135.0,0.985,New York Yankees,Yankee Stadium III,3193795.0,99,101,NYY,NYA,NYA
2782,2015,AL,BAL,BAL,E,3,162,78.0,81,81,...,134.0,0.987,Baltimore Orioles,Oriole Park at Camden Yards,2281202.0,103,104,BAL,BAL,BAL
2783,2015,AL,TBA,TBD,E,4,162,84.0,80,82,...,118.0,0.984,Tampa Bay Rays,Tropicana Field,1287054.0,100,102,TBR,TBA,TBA
2784,2015,AL,BOS,BOS,E,5,162,81.0,78,84,...,148.0,0.984,Boston Red Sox,Fenway Park II,2880694.0,104,107,BOS,BOS,BOS
2785,2015,AL,TEX,TEX,W,1,162,81.0,88,74,...,169.0,0.981,Texas Rangers,Rangers Ballpark in Arlington,2491875.0,102,105,TEX,TEX,TEX
2786,2015,AL,HOU,HOU,W,2,162,81.0,86,76,...,131.0,0.986,Houston Astros,Minute Maid Park,2153585.0,97,99,HOU,HOU,HOU
2787,2015,AL,LAA,ANA,W,3,162,81.0,85,77,...,108.0,0.984,Los Angeles Angels of Anaheim,Angel Stadium of Anaheim,3012765.0,94,95,LAA,ANA,ANA
2788,2015,AL,SEA,SEA,W,4,162,81.0,76,86,...,155.0,0.985,Seattle Mariners,Safeco Field,2193581.0,92,94,SEA,SEA,SEA
2789,2015,AL,OAK,OAK,W,5,162,81.0,68,94,...,154.0,0.979,Oakland Athletics,O.co Coliseum,1768175.0,97,98,OAK,OAK,OAK
2790,2015,NL,SLN,STL,C,1,162,81.0,100,62,...,159.0,0.984,St. Louis Cardinals,Busch Stadium III,3520889.0,102,101,STL,SLN,SLN
2791,2015,NL,PIT,PIT,C,2,162,81.0,98,64,...,177.0,0.981,Pittsburgh Pirates,PNC Park,2498596.0,99,97,PIT,PIT,PIT
2792,2015,NL,CHN,CHC,C,3,162,81.0,97,65,...,120.0,0.982,Chicago Cubs,Wrigley Field,2959812.0,100,101,CHC,CHN,CHN
2793,2015,NL,MIL,MIL,C,4,162,81.0,68,94,...,164.0,0.981,Milwaukee Brewers,Miller Park,2542558.0,101,101,MIL,ML4,MIL
2794,2015,NL,CIN,CIN,C,5,162,81.0,64,98,...,131.0,0.985,Cincinnati Reds,Great American Ball Park,2419506.0,101,101,CIN,CIN,CIN
2795,2015,NL,NYN,NYM,E,1,162,81.0,90,72,...,131.0,0.986,New York Mets,Citi Field,2569753.0,94,92,NYM,NYN,NYN
2796,2015,NL,WAS,WSN,E,2,162,81.0,83,79,...,125.0,0.985,Washington Nationals,Nationals Park,2619843.0,102,99,WSN,MON,WAS
2797,2015,NL,MIA,FLA,E,3,162,81.0,71,91,...,162.0,0.987,Miami Marlins,Marlins Park,1752235.0,98,97,MIA,FLO,MIA
2798,2015,NL,ATL,ATL,E,4,162,81.0,67,95,...,186.0,0.985,Atlanta Braves,Turner Field,2001392.0,97,97,ATL,ATL,ATL
2799,2015,NL,PHI,PHI,E,5,162,81.0,63,99,...,145.0,0.981,Philadelphia Phillies,Citizens Bank Park,1831080.0,98,98,PHI,PHI,PHI
2800,2015,NL,LAN,LAD,W,1,162,81.0,92,70,...,133.0,0.988,Los Angeles Dodgers,Dodger Stadium,3764815.0,101,98,LAD,LAN,LAN
2801,2015,NL,SFN,SFG,W,2,162,81.0,84,78,...,145.0,0.987,San Francisco Giants,AT&T Park,3375882.0,99,97,SFG,SFN,SFN
2802,2015,NL,ARI,ARI,W,3,162,81.0,79,83,...,146.0,0.986,Arizona Diamondbacks,Chase Field,2080145.0,107,106,ARI,ARI,ARI
2803,2015,NL,SDN,SDP,W,4,162,81.0,74,88,...,138.0,0.985,San Diego Padres,Petco Park,2459742.0,98,97,SDP,SDN,SDN
2804,2015,NL,COL,COL,W,5,162,81.0,68,94,...,171.0,0.985,Colorado Rockies,Coors Field,2506789.0,119,118,COL,COL,COL

### There were strikes in 1972, 1981, 1985, 1990, and 1994-1995.  While there was a slight reduction of games played during this time, the 1994 season was the only one that lacked post-season play.  Therefore, the data associated with 1994 should be removed.  
    # Check the number of entries from 1994
    # Remove entries from 1994.
    # Verify that the right number of entries were removed.

In [3]:
# Check the number of entries.
count = 0
for entry in df["yearID"]:  
    if entry == 1994:
        count += 1
print (count)

28

In [4]:
# Remove the 28 entries.  Verify that 28 records were removed.
a = len(df)
df1 = df[df.yearID != 1994]
b = len(df1)
print (a)
print (b)
print (a-b)

2805
2777
28

### In order to analyze current baseball with past baseball, it is important to have a cut off year for when modern baseball started.  This, however is fraught with controversy.
    # People use the 1900 cut off year for modern baseball.  However, there were different rules during that time period.  For example: spit balls were allowed, foul balls were not counted as strikes, the distance to the pitchers mound was different, power hitters weren't significant, and most importantly, the stats we use today were not recorded (includes ERA, RBI, etc.).
        # Despite these differences, 1900 seems to be a decent cut off point for most.
    # Others argue that the 1969 cut off year should be used to define modern baseball.  Their reasoning in using this year is that spit balls were not allowed, foul balls were counted as strikes, the distance to the pitchers mound was standardized, power hitters were significant, and key stats were recorded (ERA, RBI, etc.).
        # Not many use this particular cut off date, but it seems reasonable due to its similarity to current baseball rules.
        
### Try to analyze both cut off years to determine if either yields a better trend.
### Discovered that the first World Series was played in 1903.  But wasn't a regular thing until 1905.  Start at 1905 instead of 1900.

### Make two different lists: one where the date starts at 1905 and one where the date starts at 1969.
    # Check the number of entries from 1905/1969.
    # Remove entries before 1905/1969.
    # Verify that the right number of entries were removed.
    # Export the two dataframes for later use.

In [5]:
# Check the number of records for 1905 to current year.
count = 0
for entry in df1["yearID"]:  
    if entry < 1905:
        count += 1
print (count)

447

In [6]:
# Remove records less than 1905.  Verify that 447 records were removed.
a = len(df1)
df2 = df1[df1.yearID >= 1905]
b = len(df2)
print (a)
print (b)
print (a-b)

2777
2330
447

In [7]:
# df2 contains records greater than 1900.
df2 = df2.reset_index()
df2.to_csv("../clean_data/1905.csv")
df2.head()

,index,yearID,lgID,teamID,franchID,divID,Rank,G,Ghome,W,...,DP,FP,name,park,attendance,BPF,PPF,teamIDBR,teamIDlahman45,teamIDretro
0,447,1905,AL,BOS,BOS,NaN,4,153,77.0,78,...,75.0,0.95,Boston Americans,Huntington Avenue Grounds,468828.0,101,102,BOS,BOS,BOS
1,448,1905,NL,BRO,LAD,NaN,8,155,77.0,48,...,101.0,0.93,Brooklyn Superbas,Washington Park III,227924.0,93,96,BRO,BRO,BRO
2,449,1905,NL,BSN,ATL,NaN,7,156,76.0,51,...,89.0,0.95,Boston Beaneaters,South End Grounds III,150003.0,98,103,BSN,BSN,BSN
3,450,1905,AL,CHA,CHW,NaN,2,158,82.0,92,...,64.0,0.96,Chicago White Sox,South Side Park II,687419.0,96,93,CHW,CHA,CHA
4,451,1905,NL,CHN,CHC,NaN,3,155,81.0,92,...,99.0,0.96,Chicago Cubs,West Side Park II,509900.0,104,99,CHC,CHN,CHN

In [8]:
# Check the number of records for 1969 to the current year.
count = 0 
for entry in df1["yearID"]:
    if entry < 1969:
        count += 1
print (count)

1517

In [9]:
# Remove records less than 1969.  Verify that 1517 records were removed.
a = len(df1)
df3 = df1[df1.yearID >= 1969]
b = len(df3)
print (a)
print (b)
print (a-b)

2777
1260
1517

In [10]:
# Df3 contains records greater than 1969.
df3 = df3.reset_index()
df3.to_csv("../clean_data/1969.csv")
df3.head()

,index,yearID,lgID,teamID,franchID,divID,Rank,G,Ghome,W,...,DP,FP,name,park,attendance,BPF,PPF,teamIDBR,teamIDlahman45,teamIDretro
0,1517,1969,NL,ATL,ATL,W,1,162,81.0,93,...,114.0,0.98,Atlanta Braves,Atlanta-Fulton County Stadium,1458320.0,101,101,ATL,ATL,ATL
1,1518,1969,AL,BAL,BAL,E,1,162,81.0,109,...,145.0,0.98,Baltimore Orioles,Memorial Stadium,1062069.0,101,99,BAL,BAL,BAL
2,1519,1969,AL,BOS,BOS,E,3,162,81.0,87,...,178.0,0.97,Boston Red Sox,Fenway Park II,1833246.0,107,106,BOS,BOS,BOS
3,1520,1969,AL,CAL,ANA,W,3,163,81.0,71,...,164.0,0.97,California Angels,Anaheim Stadium,758388.0,94,95,CAL,CAL,CAL
4,1521,1969,AL,CHA,CHW,W,5,162,81.0,68,...,163.0,0.98,Chicago White Sox,Comiskey Park,589546.0,106,107,CHW,CHA,CHA

### Gather the winners of the World Series.
    # Collect data in list for ws_win_percentage.
    # Collect data in list for nonws_win_percentage.
    # Collect data in list for total_win_percentage.
    # Turn data into dataframes.

In [11]:
# Make a list of World Series and non-World Series winners percent win for 1905 onwards.
ws_win_percentage_1905 = []
nonws_win_percentage_1905 = []
for entry in range(len(df2)):
    if df2["WSWin"][entry] == "Y":
        win = df2["W"][entry]
        total = df2["G"][entry]
        percent = int((win/total) * 100)
        ws_win_percentage_1905.append(percent)
    elif df2["WSWin"][entry] == "N":
        win = df2["W"][entry]
        total = df2["G"][entry]
        percent = int((win/total) *100)
        nonws_win_percentage_1905.append(percent)

In [12]:
# Make a list of World Series and non-World Series winners percent win for 1969 onwards.
ws_win_percentage_1969 = []
nonws_win_percentage_1969 = []
for entry in range(len(df3)):
    if df3["WSWin"][entry] == "Y":
        win = df3["W"][entry]
        total = df3["G"][entry]
        percent = int((win/total) * 100)
        ws_win_percentage_1969.append(percent)
    if df3["WSWin"][entry] == "N":
        win = df3["W"][entry]
        total = df3["G"][entry]
        percent = int((win/total) *100)
        nonws_win_percentage_1969.append(percent)

In [13]:
# Make a list of total percent wins for 1905 onwards.
total_wins_1905 = []
for entry in range(len(df2)):
    win = df2["W"][entry]
    total = df2["G"][entry]
    percent = int((win/total) * 100)
    total_wins_1905.append(percent)

In [14]:
# Make a list of total percent wins for 1969 onwards.
total_wins_1969 = []
for entry in range(len(df3)):
    win = df3["W"][entry]
    total = df3["G"][entry]
    percent = int((win/total) * 100)
    total_wins_1969.append(percent)

In [15]:
# Find percent wins frequency of World Series winners 1905 onwards.  Set up dataframe.
ws_win_counter_1905 = Counter(ws_win_percentage_1905)
wswin_1905 = pd.Series(ws_win_counter_1905, index = ws_win_counter_1905.keys())
wswin_1905 = wswin_1905.reset_index()
wswin_1905 = wswin_1905.rename(columns = {"index": "Percentage", 0: "Count"})

In [16]:
# Find percent wins frequence of non-World Series winners 1905 onwards.  Set up dataframe.
ws_nowin_counter_1905 = Counter(nonws_win_percentage_1905)
nowswin_1905 = pd.Series(ws_nowin_counter_1905, index = ws_nowin_counter_1905.keys())
nowswin_1905 = nowswin_1905.reset_index()
nowswin_1905 = nowswin_1905.rename(columns = {"index": "Percentage", 0: "Count"})

In [17]:
# Find percent wins frequency of World Series winners 1969 onwards.  Set up dataframe.
ws_win_counter_1969 = Counter(ws_win_percentage_1969)
wswin_1969 = pd.Series(ws_win_counter_1969, index = ws_win_counter_1969.keys())
wswin_1969 = wswin_1969.reset_index()
wswin_1969 = wswin_1969.rename(columns = {"index": "Percentage", 0: "Count"})

In [18]:
# Find percent wins frequency of non-World Series winners 1969 onwards.  Set up dataframe.
ws_nowin_counter_1969 = Counter(nonws_win_percentage_1969)
nowswin_1969 = pd.Series(ws_nowin_counter_1969, index = ws_nowin_counter_1969.keys())
nowswin_1969 = nowswin_1969.reset_index()
nowswin_1969 = nowswin_1969.rename(columns = {"index": "Percentage", 0: "Count"})

In [19]:
# Find percent wins frequency of all teams 1905 onwards.  Set up dataframe.
wins_1905 = Counter(total_wins_1905)
totwins_1905 = pd.Series(wins_1905, index = wins_1905.keys())
totwins_1905 = totwins_1905.reset_index()
totwins_1905 = totwins_1905.rename(columns = {"index": "Percentage", 0: "Count"})

In [20]:
# Find percent wins frequency for all teams 1969 onwards.  Set up dataframe.
wins_1969 = Counter(total_wins_1969)
totwins_1969 = pd.Series(wins_1969, index = wins_1969.keys())
totwins_1969 = totwins_1969.reset_index()
totwins_1969 = totwins_1969.rename(columns = {"index": "Percentage", 0: "Count"})

### Create another column for Frequency.
    # Turn the Count number into a frequency of the sample population.
    # Add the information to the dataframe.

In [21]:
# Find frequency of World Series winners of 1905 onwards.
total1 = wswin_1905["Count"].sum()
frequency1 = [x/total1 for x in wswin_1905["Count"]]
wswin_1905["Frequency"] = frequency1
wswin_1905

    Percentage  Count  Frequency
0           67      2   0.018182
1           60      8   0.072727
2           69      2   0.018182
3           62     13   0.118182
4           71      1   0.009091
5           65      6   0.054545
6           66      7   0.063636
7           68      4   0.036364
8           59     10   0.090909
9           58      9   0.081818
10          64      6   0.054545
11          63      7   0.063636
12          61     12   0.109091
13          57      3   0.027273
14          70      2   0.018182
15          56     12   0.109091
16          55      2   0.018182
17          52      1   0.009091
18          54      2   0.018182
19          51      1   0.009091

In [22]:
# Find frequency of non-World Series winners of 1905 onwards.
total2 = nowswin_1905["Count"].sum()
frequency2 = [x/total2 for x in nowswin_1905["Count"]]
nowswin_1905["Frequency"] = frequency2
nowswin_1905

    Percentage  Count  Frequency
0           50    115   0.052178
1           30      5   0.002269
2           32     20   0.009074
3           58     70   0.031760
4           59     67   0.030399
5           49     86   0.039020
6           51    110   0.049909
7           46    117   0.053085
8           60     47   0.021325
9           53    124   0.056261
10          61     35   0.015880
11          34     23   0.010436
12          37     38   0.017241
13          41     90   0.040835
14          31      8   0.003630
15          43     81   0.036751
16          74      1   0.000454
17          56     91   0.041289
18          47     72   0.032668
19          62     37   0.016788
20          52     86   0.039020
21          33     22   0.009982
22          36     18   0.008167
23          38     47   0.021325
24          42     55   0.024955
25          55     84   0.038113
26          57     59   0.026770
27          44     80   0.036298
28          48    112   0.050817
29          40     63   0.028584
30          63     12   0.005445
31          35     24   0.010889
32          29      8   0.003630
33          67      5   0.002269
34          45     95   0.043103
35          39     45   0.020417
36          26      2   0.000907
37          28      2   0.000907
38          64     13   0.005898
39          54    114   0.051724
40          66      5   0.002269
41          27      6   0.002722
42          23      1   0.000454
43          25      1   0.000454
44          69      2   0.000907
45          65      2   0.000907
46          24      2   0.000907
47          71      2   0.000907

In [23]:
# Find frequency of World Series winners of 1969 onwards.
total3 = wswin_1969["Count"].sum()
frequency3 = [x/total3 for x in wswin_1969["Count"]]
wswin_1969["Frequency"] = frequency3
wswin_1969

    Percentage  Count  Frequency
0           61      6   0.130435
1           66      3   0.065217
2           59      4   0.086957
3           60      5   0.108696
4           58      6   0.130435
5           55      2   0.043478
6           62      2   0.043478
7           56     10   0.217391
8           57      1   0.021739
9           64      1   0.021739
10          52      1   0.021739
11          70      1   0.021739
12          54      2   0.043478
13          51      1   0.021739
14          63      1   0.021739

In [24]:
# Find frequency of non-World Series winners of 1969 onwards.
total4 = nowswin_1969["Count"].sum()
frequency4 = [x/total4 for x in nowswin_1969["Count"]]
nowswin_1969["Frequency"] = frequency4
nowswin_1969

    Percentage  Count  Frequency
0           57     25   0.020593
1           67      1   0.000824
2           53     73   0.060132
3           43     50   0.041186
4           41     55   0.045305
5           56     47   0.038715
6           54     85   0.070016
7           38     23   0.018946
8           55     48   0.039539
9           50     63   0.051895
10          42     28   0.023064
11          52     47   0.038715
12          59     44   0.036244
13          32      4   0.003295
14          49     42   0.034596
15          39     23   0.018946
16          46     80   0.065898
17          34      7   0.005766
18          51     75   0.061779
19          62     16   0.013180
20          48     70   0.057661
21          40     35   0.028830
22          60     19   0.015651
23          45     68   0.056013
24          63      7   0.005766
25          37     19   0.015651
26          61     14   0.011532
27          44     35   0.028830
28          35      9   0.007414
29          47     40   0.032949
30          58     39   0.032125
31          33      7   0.005766
32          36      6   0.004942
33          64      4   0.003295
34          69      1   0.000824
35          65      1   0.000824
36          71      1   0.000824
37          26      1   0.000824
38          31      2   0.001647

In [25]:
# Find frequency of all from 1905 onwards.
total5 = totwins_1905["Count"].sum()
frequency5 = [x/total5 for x in totwins_1905["Count"]]
totwins_1905["Frequency"] = frequency5
totwins_1905

    Percentage  Count  Frequency
0           50    115   0.049356
1           30      6   0.002575
2           32     20   0.008584
3           58     79   0.033906
4           59     77   0.033047
5           49     87   0.037339
6           51    113   0.048498
7           67      7   0.003004
8           46    117   0.050215
9           60     55   0.023605
10          53    124   0.053219
11          61     47   0.020172
12          34     23   0.009871
13          37     38   0.016309
14          41     91   0.039056
15          31      8   0.003433
16          43     82   0.035193
17          74      1   0.000429
18          56    104   0.044635
19          47     72   0.030901
20          62     50   0.021459
21          52     89   0.038197
22          33     22   0.009442
23          36     18   0.007725
24          38     47   0.020172
25          42     55   0.023605
26          55     89   0.038197
27          69      4   0.001717
28          57     62   0.026609
29          44     80   0.034335
30          48    113   0.048498
31          40     64   0.027468
32          63     19   0.008155
33          35     24   0.010300
34          29      8   0.003433
35          45     96   0.041202
36          71      3   0.001288
37          39     45   0.019313
38          26      2   0.000858
39          65      8   0.003433
40          28      2   0.000858
41          64     19   0.008155
42          66     12   0.005150
43          54    117   0.050215
44          68      4   0.001717
45          27      6   0.002575
46          23      1   0.000429
47          25      1   0.000429
48          70      2   0.000858
49          24      2   0.000858

In [26]:
# Find frequency of all from 1969 onwards.
total6 = totwins_1969["Count"].sum()
frequency6 = [x/total6 for x in totwins_1969["Count"]]
totwins_1969["Frequency"] = frequency6
totwins_1969

    Percentage  Count  Frequency
0           57     26   0.020635
1           67      1   0.000794
2           53     73   0.057937
3           43     50   0.039683
4           41     55   0.043651
5           56     57   0.045238
6           54     87   0.069048
7           38     23   0.018254
8           55     50   0.039683
9           50     63   0.050000
10          42     28   0.022222
11          52     48   0.038095
12          59     48   0.038095
13          32      4   0.003175
14          49     42   0.033333
15          61     20   0.015873
16          39     23   0.018254
17          46     80   0.063492
18          66      3   0.002381
19          34      7   0.005556
20          51     76   0.060317
21          62     18   0.014286
22          48     70   0.055556
23          40     35   0.027778
24          60     24   0.019048
25          45     68   0.053968
26          63      8   0.006349
27          37     19   0.015079
28          44     35   0.027778
29          35      9   0.007143
30          47     40   0.031746
31          58     45   0.035714
32          33      7   0.005556
33          36      6   0.004762
34          64      5   0.003968
35          69      1   0.000794
36          65      1   0.000794
37          70      1   0.000794
38          71      1   0.000794
39          26      1   0.000794
40          31      2   0.001587

### Export data for later analysis by bar chart.

In [27]:
wswin_1905.to_csv("../clean_data/wswin_1905win.csv")
nowswin_1905.to_csv("../clean_data/nowswin_1905win.csv")
wswin_1969.to_csv("../clean_data/wswin_1969win.csv")
nowswin_1969.to_csv("../clean_data/nowswin_1969win.csv")
totwins_1905.to_csv("../clean_data/totwins_1905win.csv")
totwins_1969.to_csv("../clean_data/totwins_1969win.csv")